name: Hello World Docker
author: Test
description: Desc
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: Someone
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
